### ISSUE TITLE
bug: can't handle top-level "abi" key in .json interfaces

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#4231]
### Version Information

* vyper Version (output of `vyper --version`): 0.4.0
* OS: linux
* Python Version (output of `python --version`): 3.11.9

### What's your issue about?

```py
CompilerPanic:unhandled exception 'str' object has no attribute 'get'

  contract "contracts/StreamManager.vy:23", line 23:0 
       22
  ---> 23 from . import Validator
  --------^
       24
```

**Comment by fubuloubu** [comment]
actually I think that `Validator` is a json file

**Comment by charles-cooper** [comment]
compiling with `-v` shows the problem --
```
  File "/home/charles/vyper/vyper/semantics/types/module.py", line 212, in <listcomp>
    for item in [i for i in abi if i.get("type") == "function"]:
                                   ^^^^^
vyper.exceptions.CompilerPanic: unhandled exception 'str' object has no attribute 'get'

  contract "tmp/StreamManager.vy:1", line 1:0 
  ---> 1 from . import Validator
  -------^
       2
```

**Comment by fubuloubu** [comment]
> compiling with `-v` shows the problem --
> 
> ```
>   File "/home/charles/vyper/vyper/semantics/types/module.py", line 212, in <listcomp>
>     for item in [i for i in abi if i.get("type") == "function"]:
>                                    ^^^^^
> vyper.exceptions.CompilerPanic: unhandled exception 'str' object has no attribute 'get'
> 
>   contract "tmp/StreamManager.vy:1", line 1:0 
>   ---> 1 from . import Validator
>   -------^
>        2
> ```

not sure I get it lol

**Comment by charles-cooper** [comment]
yea i mean it's not very well validated, but moving the contents of the `"abi"` key to top level (so the top level object is a list) fixes the compilation issue

**Comment by fubuloubu** [comment]
gotcha

to note for transparency though, this works in <0.4, so there is a bit of a regression not to support optional `abi` top-level key

**Comment by charles-cooper** [comment]
yea, not sure where this regression happened

**Comment by charles-cooper** [comment]
> gotcha
> 
> to note for transparency though, this works in <0.4, so there is a bit of a regression not to support optional `abi` top-level key

seems like it's not a regression - https://github.com/vyperlang/vyper/pull/4279#issuecomment-2400633840

**Comment by charles-cooper** [comment]
fixed in https://github.com/vyperlang/vyper/pull/4279
