### ISSUE TITLE
nondescriptive error raised when not intialising an interface properly

### ISSUE THREAD

**Issue by gosuto-inzasheru** [vyperlang/vyper#3166]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7
* OS: macos
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

i forgot to initialise an interface properly the other day, and compiling it gave me a very weird raise. it did not help me understand my mistake:
```
# @version 0.3.7

interface IERC20:
    def balanceOf(_owner: address) -> uint256: view

@external
def _func() -> uint256:
    bal: uint256 = IERC20.balanceOf(0x514910771AF9Ca656af840dff83E8264EcF986CA)
    return bal
```
note `IERC20` object not initialised. compiling throws:
> AttributeError: 'InterfacePrimitive' object has no attribute 'get_member'

problem can obviously be solved by initialising `IERC20` properly:
```
bal: uint256 = IERC20(0x514910771AF9Ca656af840dff83E8264EcF986CA).balanceOf(0x514910771AF9Ca656af840dff83E8264EcF986CA)
```

full trace:
```
Brownie v1.19.2 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.7
Unhandled exception in 'contracts/MinExample.vy':
  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/compile.py", line 50, in main
    proj = project.load()
  File "brownie/project/main.py", line 780, in load
    return Project(name, project_path)
  File "brownie/project/main.py", line 188, in __init__
    self.load()
  File "brownie/project/main.py", line 257, in load
    self._compile(changed, self._compiler_config, False)
  File "brownie/project/main.py", line 100, in _compile
    build_json = compiler.compile_and_format(
  File "brownie/project/compiler/__init__.py", line 141, in compile_and_format
    output_json = compile_from_input_json(input_json, silent, allow_paths)
  File "brownie/project/compiler/__init__.py", line 252, in compile_from_input_json
    return vyper.compile_from_input_json(input_json, silent, allow_paths)
  File "brownie/project/compiler/vyper.py", line 235, in compile_from_input_json
    return vyper_json.compile_json(input_json, root_path=allow_paths)
  File "vyper/cli/vyper_json.py", line 466, in compile_json
    compiler_data, warn_data = compile_from_input_dict(input_dict, exc_handler, root_path)
  File "vyper/cli/vyper_json.py", line 382, in compile_from_input_dict
    return exc_handler(contract_path, exc, "compiler"), {}
  File "vyper/cli/vyper_json.py", line 102, in exc_handler_raises
    raise exception
  File "vyper/cli/vyper_json.py", line 373, in compile_from_input_dict
    data = vyper.compile_codes(
  File "vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "vyper/compiler/__init__.py", line 143, in compile_codes
    raise exc
  File "vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "vyper/compiler/output.py", line 145, in build_abi_output
    abi = compiler_data.vyper_module_folded._metadata["type"].to_abi_dict()
  File "vyper/compiler/phases.py", line 107, in vyper_module_folded
    module, storage_layout = self._folded_module
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "vyper/compiler/phases.py", line 101, in _folded_module
    return generate_folded_ast(
  File "vyper/compiler/phases.py", line 229, in generate_folded_ast
    validate_semantics(vyper_module_folded, interface_codes)
  File "vyper/semantics/validation/__init__.py", line 11, in validate_semantics
    validate_functions(vyper_ast)
  File "vyper/semantics/validation/local.py", line 62, in validate_functions
    FunctionNodeVisitor(vy_module, node, namespace)
  File "vyper/semantics/validation/local.py", line 181, in __init__
    self.visit(node)
  File "vyper/semantics/validation/local.py", line 224, in visit
    super().visit(node)
  File "vyper/semantics/validation/base.py", line 20, in visit
    visitor_fn(node, *args)
  File "vyper/semantics/validation/local.py", line 238, in visit_AnnAssign
    validate_expected_type(node.value, type_definition)
  File "vyper/semantics/validation/utils.py", line 433, in validate_expected_type
    given_types = _ExprTypeChecker().get_possible_types_from_node(node)
  File "vyper/semantics/validation/utils.py", line 115, in get_possible_types_from_node
    types_list = fn(node)
  File "vyper/semantics/validation/utils.py", line 217, in types_from_Call
    var = self.get_exact_type_from_node(node.func, False)
  File "vyper/semantics/validation/utils.py", line 85, in get_exact_type_from_node
    types_list = self.get_possible_types_from_node(node, only_definitions)
  File "vyper/semantics/validation/utils.py", line 115, in get_possible_types_from_node
    types_list = fn(node)
  File "vyper/semantics/validation/utils.py", line 148, in types_from_Attribute
    return [var.get_member(name, node)]
AttributeError: 'InterfacePrimitive' object has no attribute 'get_member'
```

### How can it be fixed?

am afraid solving this is out of my depth for now

**Comment by gosuto-inzasheru** [comment]
ah i forget to mention that i eventually understood my mistake because i tried to compile in v0.3.3, which is a lot more descriptive:
```
Brownie v1.19.2 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.3
CompilerError: vyper returned the following errors:

Expected a literal or variable
  contract "contracts/MinExample.vy", function "_func", line 8:19 
       7 def _func() -> uint256:
  ---> 8     bal: uint256 = IERC20.balanceOf(0x514910771AF9Ca656af840dff83E8264EcF986CA)
  --------------------------^
       9     return bal
```

**Comment by tserg** [comment]
I think this has been resolved on master, which shows this error message:
```
```

**Comment by gosuto-inzasheru** [comment]
that does indeed look more informative and complete :)

assuming that that will eventually make its way to v0.3.8, i guess this can be closed :)
