### PR TITLE
Fix return optimization for nested tuple

### LINKED ISSUE #2390: Compiler error when function returns tuple containing structs
In Ethereum Python Community Discord group, fubuloubu asked me to create this issue.

### Version Information

* vyper: 0.2.12
* OS: OSX
* Python: 3.9.6

### What's your issue about?

When a function in a contract is returning a tuple of two structs, It will not compile. Here is the error: 

`AttributeError: 'StructType' object has no attribute 'typ'`

Here is sample code if you want to replicate the error:
```
struct Animal:
    location: address
    fur: uint256

struct Human:
    location: address
    height: uint256

@external
def thisDoesNotWork(_animal: Animal, _human: Human) -> (Animal, Human):
    animal: Animal = _animal
    human: Human = _human

    # do stuff, edit the structs
    animal.fur += 1
    human.height += 1

    return animal, human
```

### How can it be fixed?

fubuloubu says it's a compiler error. I don't know exactly how to fix it.

### PR DESCRIPTION
**Pull request by charles-cooper**
The optimization for tuples of base types expected anything inside a
tuple to be an int, but that's not always the case.

Luckily logic introduced in 0605abbe9 can actually be generalized to any
tuple type which has no dynamic data in the ABI encoding, so we just
remove the constraints on the child types.

### What I did
Fixes #2390 

### How to verify it
Compile the example in #2390.

### Description for the changelog
Fix type error when returning nested tuples.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]
Please add a test for returning a tuple of differnet structs

**Review by iamdefinitelyahuman — APPROVED** [review]

**Comment by charles-cooper** [comment]
> Please add a test for returning a tuple of differnet structs

@fubuloubu see https://github.com/vyperlang/vyper/pull/2392/commits/cae5490ee9102307164d4a8379a2165075b0daf7 and https://github.com/vyperlang/vyper/issues/2394 (latter explains why I didn't just include the original test cases as is)

**Review by fubuloubu — APPROVED** [review]
