### PR TITLE
Update ERC721.vy

### PR DESCRIPTION
**Pull request by mrhouzlane**
### What I did

changed bytes4 to Bytes[4] because of Error : output_type must be bytes[4] or bytes32

### How I did it
bytes4 --> Bytes[4] :

### How to verify it

vyper ERC721.vy 

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../blob/master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by charles-cooper** [comment]
`bytes4` is correct on the master branch -- in 0.3.4, method_id returns `Bytes[4]` or `bytes4`.

**Comment by mrhouzlane** [comment]
How I update to 0.3.4 ? 
I have this error : ERROR: No matching distribution found for vyper==0.3.4

**Comment by charles-cooper** [comment]
@mrzhoulane it's unreleased. if you want an example that will work with vyper 0.3.3, please check out the `examples/` directory from that tag -- https://github.com/vyperlang/vyper/tree/v0.3.3/examples

**Comment by Doc-Pixel** [comment]
> How I update to 0.3.4 ? I have this error : ERROR: No matching distribution found for vyper==0.3.4

`pip install git+https://github.com/vyperlang/vyper.git` will install the very latest version from the master branch.

Couple of things to keep in mind:
- if you're using a virtual environment, make sure it is activated when you pip install vyper
- sometimes frameworks like brownie are not 100% compatible with a pre-release vyper installation
- if you update brownie for example, it will remove any vyper version it doesn't know, so it will delete the pre-release vyper installation and install the latest official release of vyper which is 0.3.3 at the moment

Hope this helps :-)

**Comment by charles-cooper** [comment]
@mrhouzlane is this still an issue as of v0.3.4 release? otherwise, I'd like to close this PR

**Comment by mrhouzlane** [comment]
All good.

**Comment by mrhouzlane** [comment]
Having this error again : 

```output_type must be Bytes[4] or bytes4
  contract "/ERC721.vy", function "safeTransferFrom", line 278:91 
       277         # Throws if transfer destination is a contract which does not implement 'onERC721Received'
  ---> 278         assert returnValue == method_id("onERC721Received(address,address,uint256,bytes)", output_type=bytes32) ```

**Comment by charles-cooper** [comment]
you have `output_type=bytes32`. for recent (>=0.3.4) versions of vyper, output_type needs to be `bytes4`
