### ISSUE TITLE
Constant-foldable tuple index in nested subscript crashes compiler

### ISSUE THREAD

**Issue by researchzero-sec** [vyperlang/vyper#5150]
### Version Information

* vyper Version (output of `vyper --version`): 0.4.4+commit.bdf00d31
* OS: Linux Ubuntu Jammy
* Python Version: Python 3.11

### What's your issue about?

Compiling a contract where a tuple is reached through a *nested* subscript and indexed with a constant-**foldable** integer expression (e.g. `1 - 1`, `2 * 1`, or a `constant()` name) crashes the compiler with `CompilerPanic: unhandled exception` instead of compiling.

Minimal reproduction:

```vyper
m: HashMap[uint256, (uint256, uint256)]

@external
def f(k: uint256) -> uint256:
    return self.m[k][1 - 1]
```

Command run (EVM version: cancun):

```
$ vyper contract.vy
```

`vyper` exits non-zero with:

```
vyper.exceptions.CompilerPanic: unhandled exception
```

(plus the "unhandled internal compiler error … create an issue" banner). `2 * 1` and a `constant()` name reproduce identically; a bare `0` compiles.

This is a regression introduced by #4776 (`fix[lang]: fix incorrect handling of tuples in nested subscripts`, commit `63c566ec`), which was itself a fix-panic commit (pre-#4776 the same path raised `AttributeError: 'TupleT' object has no attribute 'value_type'`). Its new tuple branch at `vyper/semantics/analysis/local.py:1081-1083`:

```python
if isinstance(possible_type, TupleT):
    assert isinstance(node.slice, vy_ast.Int)  # help mypy
    value_type = possible_type.member_types[node.slice.value]
else:
    value_type = possible_type.value_type
```

relies on the assumption that "the only valid indices for tuples are constant integers, this is guaranteed by the parser." That is false for the nested path: a constant-foldable index expression is a legal compile-time constant, in range, and works as a bare literal, but reaches `local.py:1082` un-folded as a `vy_ast.Sub`/`BinOp`/`Name` node, so the bare `assert` fails and raises an empty `AssertionError`, surfaced as `CompilerPanic`.

The surrounding behaviors are all graceful, which shows this is an inconsistency rather than a forced limitation:

- `self.m[k][0]` / `[1]` (bare literal, in range) → compiles.
- `self.m[k][5]` / `[99]` (bare literal, out of range) → graceful `ArrayIndexException: Index out of range`.
- `self.m[k][i]` (variable index) → graceful `InvalidType: Tuple indexes must be literals`.
- `self.m[k][1 - 1]` / `[2 * 1]` / `[X]` (foldable constant expr, in range) → `CompilerPanic`.

### How can it be fixed?

The direct (non-nested) tuple-subscript path folds/normalises the index before this check, so `t[1 - 1]` is fine there. The nested-subscript path added by #4776 does not fold/normalise the index before reaching the `assert isinstance(node.slice, vy_ast.Int)` at `vyper/semantics/analysis/local.py:1082`. Applying the same constant-folding/normalisation of the index in the nested path before this check (so the foldable expression is reduced to a `vy_ast.Int` and an out-of-range folded value still produces a graceful `ArrayIndexException`) should resolve the panic.
